{{- if .Values.ingress.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.ingress.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .name }}  # This will access the 'name' of each host (e.g., "issy.site")
        {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.ingress.virtualService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .name }}  # This will access the 'name' of each host (e.g., "issy.site")
    {{- end }}
  gateways:
    - {{ .Values.ingress.gateway.name }}
  http:
    - match:
      - uri:
          exact: "/characters"
      route:
        - destination:
            host: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}
    - match:
        - uri:
            exact: "/healthcheck"
      route:
        - destination:
            host: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}
    - match:
        - uri:
            exact: "/htmlversion"
      route:
        - destination:
            host: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
