replicaCount: 1

image:
  repository: ecyanofsky/rick_and_morty
  pullPolicy: IfNotPresent
  tag: "1.3"

service:
  name: rick-morty-service
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  gateway:
    name: rick-morty-gateway
  enabled: true
  annotations: {}
  hosts:
    - name: "issy.site"
  port: 80
  virtualService:
    name: rick-morty-virtualservice

serviceAccount:
  create: false
  name: ""
  annotations: {}
  automount: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 60
